---
- name: "Config: Create configuration {{ bsdutils_config_file }}"
  ansible.builtin.lineinfile:
    dest: "{{ bsdutils_config_file }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    owner: "{{ bsdutils_owner }}"
    group: "{{ bsdutils_group }}"
    mode: "{{ bsdutils_config_mode }}"
    backup: true
    create: true
  loop: "{{ bsdutils_config }}"

# EOF
