---

- name: "config: Create configuration {{ bsdutils_config_file }}"
  lineinfile:
    dest: "{{ bsdutils_config_file }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    owner: "{{ bsdutils_owner }}"
    group: "{{ bsdutils_group }}"
    mode: "{{ bsdutils_config_mode }}"
    backup: yes
    create: yes
  with_items: "{{ bsdutils_config }}"

# EOF
...
