---

- import_tasks: packages.yml
  tags: bsdutils_packages

- import_tasks: source.yml
  tags: bsdutils_source

- import_tasks: config.yml
  tags: bsdutils_config

- import_tasks: copy.yml
  tags: bsdutils_copy

- import_tasks: cron.yml
  tags: bsdutils_cron

# EOF
...
