---
- name: "Packages: Install packages"
  when: freebsd_install_method == "packages"
  register: result
  community.general.pkgng:
    name: "{{ bsdutils_packages }}"
  retries: "{{ freebsd_install_retries }}"
  until: result is succeeded
  delay: "{{ freebsd_install_delay }}"

- name: "Packages: Install ports"
  when: freebsd_install_method == "ports"
  register: result
  community.general.portinstall:
    name: "{{ item }}"
    use_packages: "{{ freebsd_use_packages }}"
  loop: "{{ bsdutils_packages }}"
  retries: "{{ freebsd_install_retries }}"
  until: result is succeeded
  delay: "{{ freebsd_install_delay }}"

# EOF
