---

- name: "packages: Install packages"
  pkgng:
    name: "{{ item }}"
  loop: "{{ bsdutils_packages }}"
  when: freebsd_install_method == "packages"

- name: "packages: Install ports"
  portinstall:
    name: "{{ item }}"
    use_packages: "{{ freebsd_use_packages }}"
  loop: "{{ bsdutils_packages }}"
  when: freebsd_install_method == "ports"

# EOF
...
