---

- name: "source: Create directory for the source code {{ bsdutils_source_dest }}"
  file:
    state: directory
    path: "{{ bsdutils_source_dest }}"

- name: "source: Download sources from {{ bsdutils_source_url }}/{{ bsdutils_source_file }}"
  get_url:
    url: "{{ bsdutils_source_url }}/{{ bsdutils_source_file }}"
    dest: "{{ bsdutils_dest_file }}"
    checksum: "{{ bsdutils_source_checksum }}"

- name: "source: Stat {{ bsdutils_dest_file }}"
  stat:
    path: "{{ bsdutils_dest_file }}"
  register: result

- name: "source: Extract {{ bsdutils_dest_file }}"
  unarchive:
    src: "{{ bsdutils_dest_file }}"
    dest: "{{ bsdutils_source_dest }}"
    extra_opts: "{{ bsdutils_unarchive_extra_opts }}"
    remote_src: yes
  when: result.stat.exists

- name: "source: Create symbolic link bsd-utils to {{ bsdutils_source_dir }}"
  file:
    state: link
    src: "{{ bsdutils_source_dest }}/{{ bsdutils_source_dir }}"
    dest: "{{ bsdutils_source_dest }}/bsd-utils"
    force: yes

- name: "source: Which bash"
  command: "which bash"
  register: bsdutils_which_bash
  changed_when: False

# - debug: msg="{{ bsdutils_which_bash.stdout }}"

- name: "source: Patch {{ bsdutils_which_bash.stdout }}"
  lineinfile:
    dest: "{{ bsdutils_source_dest }}/bsd-utils/{{ item }}"
    regexp: "#!"
    line: "#!{{ bsdutils_which_bash.stdout }}"
  with_items: "{{ bsdutils_copy }}"
  when: not ansible_check_mode

# EOF
...
