---

- name: Create directory for the source code {{ bsdutils_source_dest }}
  file: >
    state="directory"
    path="{{ bsdutils_source_dest }}"

- name: Download sources from {{ bsdutils_source_url }}/{{ bsdutils_source_file }}
  get_url: >
    url="{{ bsdutils_source_url }}/{{ bsdutils_source_file }}"
    dest="{{ bsdutils_source_dest }}/bsd-utils-{{ bsdutils_source_file }}"

- name: Extract sources to {{ bsdutils_source_dest }}
  unarchive: >
    src="{{ bsdutils_source_dest }}/bsd-utils-{{ bsdutils_source_file }}"
    dest="{{ bsdutils_source_dest }}"
    copy="no"

- name: Create symbolic link bsd-utils to {{ bsdutils_source_dir }}
  file: >
    src="{{ bsdutils_source_dest }}/{{ bsdutils_source_dir }}"
    dest="{{ bsdutils_source_dest }}/bsd-utils"
    state="link"

# EOF
...
