---

- name: Create directory for the source code {{ bsdutils_source_dest }}
  file: >
    state="directory"
    path="{{ bsdutils_source_dest }}"

- name: Download sources from {{ bsdutils_source_url }}/{{ bsdutils_source_file }}
  get_url: >
    url="{{ bsdutils_source_url }}/{{ bsdutils_source_file }}"
    dest="{{ bsdutils_source_dest }}/bsd-utils-{{ bsdutils_source_file }}"

- name: Extract sources to {{ bsdutils_source_dest }}
  unarchive: >
    src="{{ bsdutils_source_dest }}/bsd-utils-{{ bsdutils_source_file }}"
    dest="{{ bsdutils_source_dest }}"
    remote_src="yes"
    extra_opts="--skip-old-files"
# changed_when: False
# TODO: Wait for fixed idempotent unarchive module

- name: Create symbolic link bsd-utils to {{ bsdutils_source_dir }}
  file: >
    src="{{ bsdutils_source_dest }}/{{ bsdutils_source_dir }}"
    dest="{{ bsdutils_source_dest }}/bsd-utils"
    state="link"
    force="yes"

- name: Which bash
  command: "which bash"
  register: bsdutils_which_bash
  changed_when: false

#- debug: msg="{{ bsdutils_which_bash.stdout }}"

- name: Patch {{ bsdutils_which_bash.stdout }}
  lineinfile: >
    dest="{{ bsdutils_source_dest }}/bsd-utils/{{ item }}"
    regexp="#!"
    line="#!{{ bsdutils_which_bash.stdout }}"
  with_items:
    - lib-mapgen
  when: not ansible_check_mode

# EOF
...
