---
- name: "Source: Create directory for the source code {{ bsdutils_source_dest }}"
  ansible.builtin.file:
    state: directory
    mode: "0755"
    path: "{{ bsdutils_source_dest }}"

- name: "Source: Download sources from {{ bsdutils_source_url ~ '/' ~ bsdutils_source_file }}"
  ansible.builtin.get_url:
    url: "{{ bsdutils_source_url }}/{{ bsdutils_source_file }}"
    dest: "{{ bsdutils_dest_file }}"
    mode: "0644"
    checksum: "{{ bsdutils_source_checksum }}"

- name: "Source: Stat {{ bsdutils_dest_file }}"
  ansible.builtin.stat:
    path: "{{ bsdutils_dest_file }}"
  register: result

- name: "Source: Extract {{ bsdutils_dest_file }}"
  ansible.builtin.unarchive:
    src: "{{ bsdutils_dest_file }}"
    dest: "{{ bsdutils_source_dest }}"
    creates: "{{ bsdutils_source_dest }}/bsd-utils-{{ bsdutils_source_version }}"
    extra_opts: "{{ bsdutils_unarchive_extra_opts }}"
    remote_src: true
  when: result.stat.exists

- name: "Source: Create symbolic link bsd-utils to {{ bsdutils_source_dir }}"
  ansible.builtin.file:
    state: link
    src: "{{ bsdutils_source_dest }}/{{ bsdutils_source_dir }}"
    dest: "{{ bsdutils_source_dest }}/bsd-utils"
    force: true

- name: "Source: Which bash"
  ansible.builtin.command:
    cmd: which bash
  register: bsdutils_which_bash
  changed_when: false

# - debug: msg="{{ bsdutils_which_bash.stdout }}"

- name: "Source: Patch {{ bsdutils_which_bash.stdout }}"
  ansible.builtin.lineinfile:
    dest: "{{ bsdutils_source_dest }}/bsd-utils/{{ item }}"
    regexp: "#!"
    line: "#!{{ bsdutils_which_bash.stdout }}"
  with_items: "{{ bsdutils_copy }}"
  when: not ansible_check_mode

# EOF
